on:
  push:
    branches:
      - main

name: release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: pip-resolved
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"test","section":"Improvements","hidden":false},{"type":"refactor","section":"Improvements","hidden":false},{"type":"ci","section":"Process Automation","hidden":false}]'

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Python 3.10
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pypa/build
        if: ${{ steps.release.outputs.release_created }}
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        if: ${{ steps.release.outputs.release_created }}
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: Publish distribution 📦 to Test PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
